audit_header: false
title: CrossCountry Mortgage Video Blog with Joe Dimeo
description: >-
  Our mission at CrossCountry Mortgage, LLC is to be your best resource for
  Portland Mortgage advice. Whether you are a buyer, seller, or investor, our
  team of professionals can answer any questions you might have about Mortgage.
  If you are looking to buy or sell a home, you can get all the information and
  the latest updates, tips, and tricks from CrossCountry Mortgage, LLC your
  professional Portland Mortgage Agents.
show_custom_links: true
custom_links:
  - title: Loan Types
    url: 'https://crosscountrymortgage.com/loan-types/'
  - title: Events
    url: /events/
  - title: FAQ
    url: 'https://crosscountrymortgage.com/resource-center/faq/'
  - title: Videos
    url: /videos/
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: Loans for Pets
    url: 'https://www.loansforpets.com/'
client:
  name: Joe Dimeo
  title: NMLS- 1836302
  license_number: Branch NMLS1841888
  about_markdown: >-
    Whether you’re looking to buy, build or refinance your home, our experienced
    mortgage professionals are here to help. Here at CrossCountry Mortgage, we
    offer a variety of loan options that can help you achieve homeownership with
    the speed and service you deserve. Plus, our mortgage professionals are
    dedicated to finding the right loan with great rates, terms and costs to
    meet your specific needs.


    Financing a home is one of the biggest commitments you will ever make - let
    us help guide you throughout the entire loan process from application to
    closing and beyond. We look forward to putting our mortgage service to work
    for you\!
  brand: Finance of America Mortgage
  brokerage:
  market: Portland
  address: '14945 SW Sequoia Parkway, Suite 150 Portland, OR 97224'
  phone: 720-775-7594
  phone_type: Direct
  phone2: 503-765-1166
  phone2_type: Office
  email: joe.dimeo@myccmortgage.com
  url: 'http://joedimeoloans.com'
CTAs:
  first_CTA_text: Apply Now
  first_CTA_URL: 'https://crosscountrymortgage.com/Portland-OR-5403/Joe-Dimeo/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Mortgage Loan Application
    CTA_link_text: Apply Now
    CTA_url: 'https://crosscountrymortgage.com/Portland-OR-5403/Joe-Dimeo/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/JoeDimeoLoans/'
  linkedin_url:
  youtube_url: 'https://www.youtube.com/channel/UCY3onqh-QdKbtnnG9haHbSg'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: >-
    https://podcasts.apple.com/us/podcast/portland-mortgage-podcast-with-joe-dimeo/id1479577919
podcast:
  title: Portland Mortgage Podcast with Joe Dimeo
  categories:
    - Education
  image: /uploads/dimeo-email3-1.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Portland
    Area Mortgage Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from CrossCountry Mortgage - your
    professional Portland Mortgage Agents.
  keywords: >-
    Mortgage for sale, Mortgage agents, top Mortgage agents, local Mortgage
    agents, find a Mortgage agent, houses for sale in Portland, home selling
    tips, home for sale, home buying, home buying process, property finder,
    property search, property, Mortgage market, estate agent, realestate,
    Mortgage listings, buying a house, homes for sale, mls, home buyer
  author: Joe Dimeo
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: (720) 775-7594
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#20346a'
  theme_color: '#11966e'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'